name: docker push containers to dockerhub and ecr

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  docker-push-containers-to-dockerhub-and-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: get repo name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build docker image and push to DockerHub
        uses: senzing-factory/github-action-docker-buildx-build@29-skern
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          image-tag: ${{ github.ref_name }}
          login-to-ecr: true
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          push: true
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: arn:aws:iam::${{ secrets.AWS_DOCKER_ACCOUNT_ID }}:role/github-actions-ecr-push
          sign-image: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
